PeerOrgs:
  - Name: voteOrg2
    Domain: voteOrg2.blockvote.com
    MSPDir: votingOrganizations/participantOrganizations/voteOrg2.blockvote.com/msp
    EnableNodeOUs: true #enable identity classification
    Template:
      Count: 1
      SANS:
        - localhost
    Users:
      Count: 1
